import { GroupByOptionsWithElement } from "rxjs";

export class InboxDTO {
  UserExists: boolean;
  IsOwner: number;
  SelectedLabels: string;
  IsTag: boolean;
  isPin: boolean;
  MemoSource: number;
  datasetxml: string
  CompanyId: string
  CompanyName: string
  count: number;
  AnnouncementDocId: number;
  Status: string;
  AnnouncementStatus: boolean;
  UserId: number
  FromUser: string
  UserName: string
  SubjectJson: string;
  Read_F: boolean
  Conversation_F: boolean
  All: boolean
  PageSize: number
  PageNumber: number
  FlagId: number
  Description: string
  TextContent: string
  Search: string
  FromUserId: number
  ByFilters: boolean
  FilterValues: string
  PinMemosJson: string;
  AnnoucementJson: string;
  TotalUserJson: string;
  ReadUserJson: any;
  SuggestionJson: string;
  AnnouncementUrl: string;
  LablesJson: string;
  MemosJSON: string
  LabelMemosJson: string
  FiltersJSON: string
  TotalRecordsJSON: string
  CompanyListJSON: string
  UserListJSON: string
  StatusJSON: string
  PinStatus: boolean
  PUserJson: string
  PCompanyJson: string
  PStatusJson: string
  PolicyId: number;
  IsFiltered: boolean;
  CreatedBy: number
  MailId: any
  MemoDetailsJson: string
  ReplyListJson: string
  FinalMemoReply: string
  ReplyFiltersUsers: string;
  BasicMemoDetailsJson: string
  RemainingUsersListJson: string
  TotalUsersJson: string
  SentUser: string
  SentUserId: number
  ReplyId: number
  IsReplyFilter: boolean;
  ReplyDetailsJson: string
  UserApprovalStatus: string;
  message: string
  Favorite: boolean
  MemoFrom: string
  BannerJson: string;
  ReplyPending_F: boolean
  ApprovalPending_F: boolean
  IsConfidential: boolean
  Expired_F: boolean
  organizationid: number
  UserJson: string
  request: FormData
  AttachmentJson: string
  TotaluserCount: string;
  Readuser: string
  ConversationJson: string
  daysJson: string
  HistoryJson: string
  UserReplied: number
  Purpose: string
  Attachment: boolean
  ConversationCount: number
  Conversation: number
  ActualStatus: string
  Subject: string
  FavoriteMemo: boolean
  UserIds: string
  title: string
  body: string
  icon: string
  NotificationStatus: boolean
  IsDeleted: boolean
  MailView: boolean
  InboxMemosType: string
  OrderBy: string
  NewMemosJSON: string
  LabelName: string
  LabelId: number
  IsActive: boolean
  DesignationName: string
  DisplayName: string
  JsonData: string
  UserMemoNature: string
  RoleId: number
  CategoryName: string
  DraftText: string;
  Data: string;
  DraftId: string
  ViewAll: boolean
  ReplyFilter_AllMain: boolean;
  ReplyFilter_Unread: boolean;
  ReplyFilter_Approval: boolean;
  ReplyFilter_ReplyRrquired: boolean;
  ReplyFilter_Date: boolean;
  ReplyFilter_Subject: boolean;
  ReplyFilter_From: boolean;
  ReplyFilter_ByMe: boolean;
  ReplyFilter_Attachment: boolean;
  ReplyFilter_ByMeWithActions: boolean;
  ReplyFilter_Bookmarks: boolean;
  Url: string
  ReplyHistoryJson: string
  UnRead: boolean
  PolicyHeader: string
  PolicyContent: string
  IsPolicy: boolean
  ToUserId: number;
  OrganizationId: number;
  AnnouncementId: number
  MailIds: string;
  labelIds: string;
  checked: boolean;
  check: unknown
  IsExist: boolean;
  SuggestionId: number;
  DraftIds: string;
  SortType: number;
  OptionId: number;
  PopupId: number;
  AttachmentData: string;
  IsAll: boolean;
  IsCompany: boolean;
  IsDepartment: boolean;
  IsDesignation: boolean;
  CompanyIds: string;
  DepartmentIds: string;
  DesignationIds: string;
  ReportingUserId: number;
  IsReportingUser: boolean;
  StartDateTime: Date;
  EndDateTime: Date;
  Suggestionjson: string;
  AnnoucementStatus: boolean;
  BannerName: string;
  BannerUrl: string;
  BannerId: number;
  StartDate: any;
  EndDate: any;
  StartDates: any;
  EndDates: any;
  AnnoucementCount: number;
  ReadCount: number;
  MergeSubject: string;
  ReplyIds: string;
  PreviousSubject: string;
  OptioinId: number;
  Comments: string;
  RequestJson: string
  DMSRequestJson: string;
  createdby: number;
  PendingCount: number;
  UserRequest: boolean;
  MailDocId: number;
  MemoDateTime: any;
  IsReply: boolean;
  Mailids: string;
  HasAttachment: boolean;
  startdate: string;
  enddate: string;
  MailDocIdString: number;
  Reply: boolean;
  DeadLineDate: Date;
  DocumentId: number;
  ParentId: number;
  ToUserxml: any;
  Deadline_sort: number;
  Title: string;
  CCUserxml: any;
  ReferenceNo: any;
  MemoReplyType: string;
  LastReplyId: number;
  ToUsersString: string;
  NewMemosTrigger: string;
  NewRepliesTrigger: string;
  pageSize: number;
  pageNumber: number;
  lastCreatedDate: any;
  Searchtxt: string;
  FromUserIds: string;
  Source: string;
  IsApprovalPending: boolean;
  IsReplyRequired: boolean;
  IsExpired: boolean;
  url: string;
  userIds: string;
  FeatureId: number;
  MemoType: string
  uniqueid: number;
  TotalReplyRecords: number;
  Activity: boolean;
  LastRowId: number;
  startDate: string;
  endDate: string;
  DocumentIds: string;
  labelId: number;
  ShareDocumentJson: string;
  mailid: number;
  sorttype: string;
  Replied: boolean;
  IsPolicyDocument: boolean;
  WorkflowName: string;
  AttachmentRequired: boolean;
  ActionType: string;
  Note: string;
  CreatedByEmployeeId: number;
  UserListJson: string;
  UserActions: string;
  WorkFlowId: number;
  EmployeeId: number;
  WorkFlowJson: string;
  SortId: any;
  GroupId: any;
  ReplyWorkFlowSortId: any;
  Urls:any;
  ShareId:number;
}
